version: "3.9"

services:
    database:
      image: postgres
      container_name: database-dinnerDelivery
      restart: always
      ports: 
        - 1999:5432
      environment:
        - POSTGRES_USER=docker
        - POSTGRES_PASSWORD=YWfv44186uG6oBetxJC7sOAxJttd6aLe0zpmb_xdwpQ
        - POSTGRES_DB=dinnerDelivery
      volumes:
        - pgdata:/data/postgres

        - ./src/shared/infra/typeorm/sql/create_base_test.sql:/docker-entrypoint-initdb.d/create_tables.sql
        
    redis:
        image: redis:alpine
        container_name: redis
        ports: 
            - 6379:6379
        volumes:
            - redis:/data
volumes:
  pgdata:
    driver: local
  redis:
    driver: local

  
