version: "3.9"

services:
    database:
      image: postgres
      container_name: database-dinnerDelivery
      restart: always
      ports: 
        - 1999:5432
      environment:
        - POSTGRES_USER=docker
        - POSTGRES_PASSWORD=YWfv44186uG6oBetxJC7sOAxJttd6aLe0zpmb_xdwpQ
        - POSTGRES_DB=dinnerDelivery
      volumes:
        - pgdata:/data/postgres

        - ./src/shared/infra/typeorm/sql/create_base_test.sql:/docker-entrypoint-initdb.d/create_tables.sql

volumes:
  pgdata:
    driver: local


  
