name: CI
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          
      - name: Install Dependencies
        run: yarn
        
      - name: Build
        run: yarn build
    
      - name: Up Container Postgres/Redis
        run: docker-compose up -d

      - name: Run Migrations
        run: yarn migration:run
      
      - name: Run Tests
        run: yarn test
              
      - uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          source: "., !node_modules"
          target: "~/app/api-dinnerdelivery"

      - name: Update all package
        uses: appleboy/ssh-action@master
        with:
            host: ${{ secrets.SSH_HOST }}
            username: ${{ secrets.SSH_USER }}
            port: ${{ secrets.SSH_PORT }}
            key: ${{ secrets.SSH_KEY }}
            script: |
              cd ~/app/api-dinnerdelivery
              yarn
              yarn migration:run
              pm2 restart dinnerDelivery
